[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../database" }
actix-cors.workspace = true
actix-web.workspace = true
chrono.workspace = true
diesel.workspace = true
dotenvy.workspace = true
serde.workspace = true
