[package]
name = "database"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Polak <contact@matteopolak.com>"]
description = "Database for the project"

[dependencies]
chrono = "0.4.23"
diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }
