[package]
name = "database"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Polak <contact@matteopolak.com>"]
description = "Database for the project"

[dependencies]
chrono.workspace = true
diesel.workspace = true
