[package]
name = "checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.13", features = ["json", "gzip"] }
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7.7"
api = { path = "../api" }
chrono = "0.4.23"
serde = { version = "1.0.152", features = ["derive"] }
once_cell = "1.17.0"
