[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
chrono = "0.4.23"
once_cell = "1.17.0"
reqwest = { version = "0.11.14", features = ["gzip", "json"] }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde-aux = "4.1.2"
serde_json = "1.0.91"
serde_qs = "0.11.0"
